# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_avio505_swig', [dirname(__file__)])
        except ImportError:
            import _avio505_swig
            return _avio505_swig
        if fp is not None:
            try:
                _mod = imp.load_module('_avio505_swig', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _avio505_swig = swig_import_helper()
    del swig_import_helper
else:
    import _avio505_swig
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


def _swig_setattr_nondynamic_method(set):
    def set_attr(self,name,value):
        if (name == "thisown"): return self.this.own(value)
        if hasattr(self,name) or (name == "this"):
            set(self,name,value)
        else:
            raise AttributeError("You cannot add attributes to %s" % self)
    return set_attr



def high_res_timer_now():
  """high_res_timer_now() -> gr::high_res_timer_type"""
  return _avio505_swig.high_res_timer_now()

def high_res_timer_now_perfmon():
  """high_res_timer_now_perfmon() -> gr::high_res_timer_type"""
  return _avio505_swig.high_res_timer_now_perfmon()

def high_res_timer_tps():
  """high_res_timer_tps() -> gr::high_res_timer_type"""
  return _avio505_swig.high_res_timer_tps()

def high_res_timer_epoch():
  """high_res_timer_epoch() -> gr::high_res_timer_type"""
  return _avio505_swig.high_res_timer_epoch()
class three_ch_multip_rtdex(object):
    """<+description of block+>"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def make():
        """
        make() -> three_ch_multip_rtdex_sptr

        Return a shared_ptr to a new instance of avio505::three_ch_multip_rtdex.

        To avoid accidental use of raw pointers, avio505::three_ch_multip_rtdex's constructor is in a private implementation class. avio505::three_ch_multip_rtdex::make is the public interface for creating new instances.

        Params: (NONE)
        """
        return _avio505_swig.three_ch_multip_rtdex_make()

    make = staticmethod(make)
    __swig_destroy__ = _avio505_swig.delete_three_ch_multip_rtdex
    __del__ = lambda self : None;
three_ch_multip_rtdex_swigregister = _avio505_swig.three_ch_multip_rtdex_swigregister
three_ch_multip_rtdex_swigregister(three_ch_multip_rtdex)

def three_ch_multip_rtdex_make():
  """
    three_ch_multip_rtdex_make() -> three_ch_multip_rtdex_sptr

    Return a shared_ptr to a new instance of avio505::three_ch_multip_rtdex.

    To avoid accidental use of raw pointers, avio505::three_ch_multip_rtdex's constructor is in a private implementation class. avio505::three_ch_multip_rtdex::make is the public interface for creating new instances.

    Params: (NONE)
    """
  return _avio505_swig.three_ch_multip_rtdex_make()

class three_ch_multip_rtdex_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::avio505::three_ch_multip_rtdex)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::avio505::three_ch_multip_rtdex)> self) -> three_ch_multip_rtdex_sptr
        __init__(boost::shared_ptr<(gr::avio505::three_ch_multip_rtdex)> self, three_ch_multip_rtdex p) -> three_ch_multip_rtdex_sptr
        """
        this = _avio505_swig.new_three_ch_multip_rtdex_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(three_ch_multip_rtdex_sptr self) -> three_ch_multip_rtdex"""
        return _avio505_swig.three_ch_multip_rtdex_sptr___deref__(self)

    __swig_destroy__ = _avio505_swig.delete_three_ch_multip_rtdex_sptr
    __del__ = lambda self : None;
    def make(self):
        """
        make(three_ch_multip_rtdex_sptr self) -> three_ch_multip_rtdex_sptr

        Return a shared_ptr to a new instance of avio505::three_ch_multip_rtdex.

        To avoid accidental use of raw pointers, avio505::three_ch_multip_rtdex's constructor is in a private implementation class. avio505::three_ch_multip_rtdex::make is the public interface for creating new instances.

        Params: (NONE)
        """
        return _avio505_swig.three_ch_multip_rtdex_sptr_make(self)

    def history(self):
        """history(three_ch_multip_rtdex_sptr self) -> unsigned int"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(three_ch_multip_rtdex_sptr self, int which, int delay)
        declare_sample_delay(three_ch_multip_rtdex_sptr self, unsigned int delay)
        """
        return _avio505_swig.three_ch_multip_rtdex_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(three_ch_multip_rtdex_sptr self, int which) -> unsigned int"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(three_ch_multip_rtdex_sptr self) -> int"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(three_ch_multip_rtdex_sptr self) -> double"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_relative_rate(self)

    def start(self):
        """start(three_ch_multip_rtdex_sptr self) -> bool"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_start(self)

    def stop(self):
        """stop(three_ch_multip_rtdex_sptr self) -> bool"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(three_ch_multip_rtdex_sptr self, unsigned int which_input) -> uint64_t"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(three_ch_multip_rtdex_sptr self, unsigned int which_output) -> uint64_t"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(three_ch_multip_rtdex_sptr self) -> int"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(three_ch_multip_rtdex_sptr self, int m)"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(three_ch_multip_rtdex_sptr self)"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(three_ch_multip_rtdex_sptr self) -> bool"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(three_ch_multip_rtdex_sptr self, int m)"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(three_ch_multip_rtdex_sptr self) -> int"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(three_ch_multip_rtdex_sptr self, int i) -> long"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(three_ch_multip_rtdex_sptr self, long max_output_buffer)
        set_max_output_buffer(three_ch_multip_rtdex_sptr self, int port, long max_output_buffer)
        """
        return _avio505_swig.three_ch_multip_rtdex_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(three_ch_multip_rtdex_sptr self, int i) -> long"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(three_ch_multip_rtdex_sptr self, long min_output_buffer)
        set_min_output_buffer(three_ch_multip_rtdex_sptr self, int port, long min_output_buffer)
        """
        return _avio505_swig.three_ch_multip_rtdex_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(three_ch_multip_rtdex_sptr self) -> float"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(three_ch_multip_rtdex_sptr self) -> float"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(three_ch_multip_rtdex_sptr self) -> float"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(three_ch_multip_rtdex_sptr self) -> float"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(three_ch_multip_rtdex_sptr self) -> float"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(three_ch_multip_rtdex_sptr self) -> float"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(three_ch_multip_rtdex_sptr self, int which) -> float
        pc_input_buffers_full(three_ch_multip_rtdex_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(three_ch_multip_rtdex_sptr self, int which) -> float
        pc_input_buffers_full_avg(three_ch_multip_rtdex_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(three_ch_multip_rtdex_sptr self, int which) -> float
        pc_input_buffers_full_var(three_ch_multip_rtdex_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(three_ch_multip_rtdex_sptr self, int which) -> float
        pc_output_buffers_full(three_ch_multip_rtdex_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(three_ch_multip_rtdex_sptr self, int which) -> float
        pc_output_buffers_full_avg(three_ch_multip_rtdex_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(three_ch_multip_rtdex_sptr self, int which) -> float
        pc_output_buffers_full_var(three_ch_multip_rtdex_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(three_ch_multip_rtdex_sptr self) -> float"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(three_ch_multip_rtdex_sptr self) -> float"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(three_ch_multip_rtdex_sptr self) -> float"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(three_ch_multip_rtdex_sptr self) -> float"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self):
        """pc_throughput_avg(three_ch_multip_rtdex_sptr self) -> float"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(three_ch_multip_rtdex_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(three_ch_multip_rtdex_sptr self)"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(three_ch_multip_rtdex_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(three_ch_multip_rtdex_sptr self) -> int"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(three_ch_multip_rtdex_sptr self) -> int"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(three_ch_multip_rtdex_sptr self, int priority) -> int"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(three_ch_multip_rtdex_sptr self) -> std::string"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_name(self)

    def symbol_name(self):
        """symbol_name(three_ch_multip_rtdex_sptr self) -> std::string"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(three_ch_multip_rtdex_sptr self) -> io_signature_sptr"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(three_ch_multip_rtdex_sptr self) -> io_signature_sptr"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(three_ch_multip_rtdex_sptr self) -> long"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(three_ch_multip_rtdex_sptr self) -> basic_block_sptr"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(three_ch_multip_rtdex_sptr self, int ninputs, int noutputs) -> bool"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(three_ch_multip_rtdex_sptr self) -> std::string"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(three_ch_multip_rtdex_sptr self, std::string name)"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(three_ch_multip_rtdex_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _avio505_swig.three_ch_multip_rtdex_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(three_ch_multip_rtdex_sptr self) -> swig_int_ptr"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(three_ch_multip_rtdex_sptr self) -> swig_int_ptr"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(three_ch_multip_rtdex_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _avio505_swig.three_ch_multip_rtdex_sptr_message_subscribers(self, *args, **kwargs)

three_ch_multip_rtdex_sptr_swigregister = _avio505_swig.three_ch_multip_rtdex_sptr_swigregister
three_ch_multip_rtdex_sptr_swigregister(three_ch_multip_rtdex_sptr)

three_ch_multip_rtdex_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
three_ch_multip_rtdex = three_ch_multip_rtdex.make;

class adc_three_ch_demux_rtdex(object):
    """<+description of block+>"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def make():
        """
        make() -> adc_three_ch_demux_rtdex_sptr

        Return a shared_ptr to a new instance of avio505::adc_three_ch_demux_rtdex.

        To avoid accidental use of raw pointers, avio505::adc_three_ch_demux_rtdex's constructor is in a private implementation class. avio505::adc_three_ch_demux_rtdex::make is the public interface for creating new instances.

        Params: (NONE)
        """
        return _avio505_swig.adc_three_ch_demux_rtdex_make()

    make = staticmethod(make)
    __swig_destroy__ = _avio505_swig.delete_adc_three_ch_demux_rtdex
    __del__ = lambda self : None;
adc_three_ch_demux_rtdex_swigregister = _avio505_swig.adc_three_ch_demux_rtdex_swigregister
adc_three_ch_demux_rtdex_swigregister(adc_three_ch_demux_rtdex)

def adc_three_ch_demux_rtdex_make():
  """
    adc_three_ch_demux_rtdex_make() -> adc_three_ch_demux_rtdex_sptr

    Return a shared_ptr to a new instance of avio505::adc_three_ch_demux_rtdex.

    To avoid accidental use of raw pointers, avio505::adc_three_ch_demux_rtdex's constructor is in a private implementation class. avio505::adc_three_ch_demux_rtdex::make is the public interface for creating new instances.

    Params: (NONE)
    """
  return _avio505_swig.adc_three_ch_demux_rtdex_make()

class adc_three_ch_demux_rtdex_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::avio505::adc_three_ch_demux_rtdex)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::avio505::adc_three_ch_demux_rtdex)> self) -> adc_three_ch_demux_rtdex_sptr
        __init__(boost::shared_ptr<(gr::avio505::adc_three_ch_demux_rtdex)> self, adc_three_ch_demux_rtdex p) -> adc_three_ch_demux_rtdex_sptr
        """
        this = _avio505_swig.new_adc_three_ch_demux_rtdex_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(adc_three_ch_demux_rtdex_sptr self) -> adc_three_ch_demux_rtdex"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr___deref__(self)

    __swig_destroy__ = _avio505_swig.delete_adc_three_ch_demux_rtdex_sptr
    __del__ = lambda self : None;
    def make(self):
        """
        make(adc_three_ch_demux_rtdex_sptr self) -> adc_three_ch_demux_rtdex_sptr

        Return a shared_ptr to a new instance of avio505::adc_three_ch_demux_rtdex.

        To avoid accidental use of raw pointers, avio505::adc_three_ch_demux_rtdex's constructor is in a private implementation class. avio505::adc_three_ch_demux_rtdex::make is the public interface for creating new instances.

        Params: (NONE)
        """
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_make(self)

    def history(self):
        """history(adc_three_ch_demux_rtdex_sptr self) -> unsigned int"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(adc_three_ch_demux_rtdex_sptr self, int which, int delay)
        declare_sample_delay(adc_three_ch_demux_rtdex_sptr self, unsigned int delay)
        """
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(adc_three_ch_demux_rtdex_sptr self, int which) -> unsigned int"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(adc_three_ch_demux_rtdex_sptr self) -> int"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(adc_three_ch_demux_rtdex_sptr self) -> double"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_relative_rate(self)

    def start(self):
        """start(adc_three_ch_demux_rtdex_sptr self) -> bool"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_start(self)

    def stop(self):
        """stop(adc_three_ch_demux_rtdex_sptr self) -> bool"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(adc_three_ch_demux_rtdex_sptr self, unsigned int which_input) -> uint64_t"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(adc_three_ch_demux_rtdex_sptr self, unsigned int which_output) -> uint64_t"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(adc_three_ch_demux_rtdex_sptr self) -> int"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(adc_three_ch_demux_rtdex_sptr self, int m)"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(adc_three_ch_demux_rtdex_sptr self)"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(adc_three_ch_demux_rtdex_sptr self) -> bool"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(adc_three_ch_demux_rtdex_sptr self, int m)"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(adc_three_ch_demux_rtdex_sptr self) -> int"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(adc_three_ch_demux_rtdex_sptr self, int i) -> long"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(adc_three_ch_demux_rtdex_sptr self, long max_output_buffer)
        set_max_output_buffer(adc_three_ch_demux_rtdex_sptr self, int port, long max_output_buffer)
        """
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(adc_three_ch_demux_rtdex_sptr self, int i) -> long"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(adc_three_ch_demux_rtdex_sptr self, long min_output_buffer)
        set_min_output_buffer(adc_three_ch_demux_rtdex_sptr self, int port, long min_output_buffer)
        """
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(adc_three_ch_demux_rtdex_sptr self) -> float"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(adc_three_ch_demux_rtdex_sptr self) -> float"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(adc_three_ch_demux_rtdex_sptr self) -> float"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(adc_three_ch_demux_rtdex_sptr self) -> float"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(adc_three_ch_demux_rtdex_sptr self) -> float"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(adc_three_ch_demux_rtdex_sptr self) -> float"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(adc_three_ch_demux_rtdex_sptr self, int which) -> float
        pc_input_buffers_full(adc_three_ch_demux_rtdex_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(adc_three_ch_demux_rtdex_sptr self, int which) -> float
        pc_input_buffers_full_avg(adc_three_ch_demux_rtdex_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(adc_three_ch_demux_rtdex_sptr self, int which) -> float
        pc_input_buffers_full_var(adc_three_ch_demux_rtdex_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(adc_three_ch_demux_rtdex_sptr self, int which) -> float
        pc_output_buffers_full(adc_three_ch_demux_rtdex_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(adc_three_ch_demux_rtdex_sptr self, int which) -> float
        pc_output_buffers_full_avg(adc_three_ch_demux_rtdex_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(adc_three_ch_demux_rtdex_sptr self, int which) -> float
        pc_output_buffers_full_var(adc_three_ch_demux_rtdex_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(adc_three_ch_demux_rtdex_sptr self) -> float"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(adc_three_ch_demux_rtdex_sptr self) -> float"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(adc_three_ch_demux_rtdex_sptr self) -> float"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(adc_three_ch_demux_rtdex_sptr self) -> float"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self):
        """pc_throughput_avg(adc_three_ch_demux_rtdex_sptr self) -> float"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(adc_three_ch_demux_rtdex_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(adc_three_ch_demux_rtdex_sptr self)"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(adc_three_ch_demux_rtdex_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(adc_three_ch_demux_rtdex_sptr self) -> int"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(adc_three_ch_demux_rtdex_sptr self) -> int"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(adc_three_ch_demux_rtdex_sptr self, int priority) -> int"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(adc_three_ch_demux_rtdex_sptr self) -> std::string"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_name(self)

    def symbol_name(self):
        """symbol_name(adc_three_ch_demux_rtdex_sptr self) -> std::string"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(adc_three_ch_demux_rtdex_sptr self) -> io_signature_sptr"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(adc_three_ch_demux_rtdex_sptr self) -> io_signature_sptr"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(adc_three_ch_demux_rtdex_sptr self) -> long"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(adc_three_ch_demux_rtdex_sptr self) -> basic_block_sptr"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(adc_three_ch_demux_rtdex_sptr self, int ninputs, int noutputs) -> bool"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(adc_three_ch_demux_rtdex_sptr self) -> std::string"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(adc_three_ch_demux_rtdex_sptr self, std::string name)"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(adc_three_ch_demux_rtdex_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(adc_three_ch_demux_rtdex_sptr self) -> swig_int_ptr"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(adc_three_ch_demux_rtdex_sptr self) -> swig_int_ptr"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(adc_three_ch_demux_rtdex_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _avio505_swig.adc_three_ch_demux_rtdex_sptr_message_subscribers(self, *args, **kwargs)

adc_three_ch_demux_rtdex_sptr_swigregister = _avio505_swig.adc_three_ch_demux_rtdex_sptr_swigregister
adc_three_ch_demux_rtdex_sptr_swigregister(adc_three_ch_demux_rtdex_sptr)

adc_three_ch_demux_rtdex_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
adc_three_ch_demux_rtdex = adc_three_ch_demux_rtdex.make;

class sink_test(object):
    """<+description of block+>"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def make():
        """
        make() -> sink_test_sptr

        Return a shared_ptr to a new instance of avio505::sink_test.

        To avoid accidental use of raw pointers, avio505::sink_test's constructor is in a private implementation class. avio505::sink_test::make is the public interface for creating new instances.

        Params: (NONE)
        """
        return _avio505_swig.sink_test_make()

    make = staticmethod(make)
    __swig_destroy__ = _avio505_swig.delete_sink_test
    __del__ = lambda self : None;
sink_test_swigregister = _avio505_swig.sink_test_swigregister
sink_test_swigregister(sink_test)

def sink_test_make():
  """
    sink_test_make() -> sink_test_sptr

    Return a shared_ptr to a new instance of avio505::sink_test.

    To avoid accidental use of raw pointers, avio505::sink_test's constructor is in a private implementation class. avio505::sink_test::make is the public interface for creating new instances.

    Params: (NONE)
    """
  return _avio505_swig.sink_test_make()

class sink_test_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::avio505::sink_test)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::avio505::sink_test)> self) -> sink_test_sptr
        __init__(boost::shared_ptr<(gr::avio505::sink_test)> self, sink_test p) -> sink_test_sptr
        """
        this = _avio505_swig.new_sink_test_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(sink_test_sptr self) -> sink_test"""
        return _avio505_swig.sink_test_sptr___deref__(self)

    __swig_destroy__ = _avio505_swig.delete_sink_test_sptr
    __del__ = lambda self : None;
    def make(self):
        """
        make(sink_test_sptr self) -> sink_test_sptr

        Return a shared_ptr to a new instance of avio505::sink_test.

        To avoid accidental use of raw pointers, avio505::sink_test's constructor is in a private implementation class. avio505::sink_test::make is the public interface for creating new instances.

        Params: (NONE)
        """
        return _avio505_swig.sink_test_sptr_make(self)

    def history(self):
        """history(sink_test_sptr self) -> unsigned int"""
        return _avio505_swig.sink_test_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(sink_test_sptr self, int which, int delay)
        declare_sample_delay(sink_test_sptr self, unsigned int delay)
        """
        return _avio505_swig.sink_test_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(sink_test_sptr self, int which) -> unsigned int"""
        return _avio505_swig.sink_test_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(sink_test_sptr self) -> int"""
        return _avio505_swig.sink_test_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(sink_test_sptr self) -> double"""
        return _avio505_swig.sink_test_sptr_relative_rate(self)

    def start(self):
        """start(sink_test_sptr self) -> bool"""
        return _avio505_swig.sink_test_sptr_start(self)

    def stop(self):
        """stop(sink_test_sptr self) -> bool"""
        return _avio505_swig.sink_test_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(sink_test_sptr self, unsigned int which_input) -> uint64_t"""
        return _avio505_swig.sink_test_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(sink_test_sptr self, unsigned int which_output) -> uint64_t"""
        return _avio505_swig.sink_test_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(sink_test_sptr self) -> int"""
        return _avio505_swig.sink_test_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(sink_test_sptr self, int m)"""
        return _avio505_swig.sink_test_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(sink_test_sptr self)"""
        return _avio505_swig.sink_test_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(sink_test_sptr self) -> bool"""
        return _avio505_swig.sink_test_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(sink_test_sptr self, int m)"""
        return _avio505_swig.sink_test_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(sink_test_sptr self) -> int"""
        return _avio505_swig.sink_test_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(sink_test_sptr self, int i) -> long"""
        return _avio505_swig.sink_test_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(sink_test_sptr self, long max_output_buffer)
        set_max_output_buffer(sink_test_sptr self, int port, long max_output_buffer)
        """
        return _avio505_swig.sink_test_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(sink_test_sptr self, int i) -> long"""
        return _avio505_swig.sink_test_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(sink_test_sptr self, long min_output_buffer)
        set_min_output_buffer(sink_test_sptr self, int port, long min_output_buffer)
        """
        return _avio505_swig.sink_test_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(sink_test_sptr self) -> float"""
        return _avio505_swig.sink_test_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(sink_test_sptr self) -> float"""
        return _avio505_swig.sink_test_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(sink_test_sptr self) -> float"""
        return _avio505_swig.sink_test_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(sink_test_sptr self) -> float"""
        return _avio505_swig.sink_test_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(sink_test_sptr self) -> float"""
        return _avio505_swig.sink_test_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(sink_test_sptr self) -> float"""
        return _avio505_swig.sink_test_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(sink_test_sptr self, int which) -> float
        pc_input_buffers_full(sink_test_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.sink_test_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(sink_test_sptr self, int which) -> float
        pc_input_buffers_full_avg(sink_test_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.sink_test_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(sink_test_sptr self, int which) -> float
        pc_input_buffers_full_var(sink_test_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.sink_test_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(sink_test_sptr self, int which) -> float
        pc_output_buffers_full(sink_test_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.sink_test_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(sink_test_sptr self, int which) -> float
        pc_output_buffers_full_avg(sink_test_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.sink_test_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(sink_test_sptr self, int which) -> float
        pc_output_buffers_full_var(sink_test_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.sink_test_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(sink_test_sptr self) -> float"""
        return _avio505_swig.sink_test_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(sink_test_sptr self) -> float"""
        return _avio505_swig.sink_test_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(sink_test_sptr self) -> float"""
        return _avio505_swig.sink_test_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(sink_test_sptr self) -> float"""
        return _avio505_swig.sink_test_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self):
        """pc_throughput_avg(sink_test_sptr self) -> float"""
        return _avio505_swig.sink_test_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(sink_test_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _avio505_swig.sink_test_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(sink_test_sptr self)"""
        return _avio505_swig.sink_test_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(sink_test_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _avio505_swig.sink_test_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(sink_test_sptr self) -> int"""
        return _avio505_swig.sink_test_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(sink_test_sptr self) -> int"""
        return _avio505_swig.sink_test_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(sink_test_sptr self, int priority) -> int"""
        return _avio505_swig.sink_test_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(sink_test_sptr self) -> std::string"""
        return _avio505_swig.sink_test_sptr_name(self)

    def symbol_name(self):
        """symbol_name(sink_test_sptr self) -> std::string"""
        return _avio505_swig.sink_test_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(sink_test_sptr self) -> io_signature_sptr"""
        return _avio505_swig.sink_test_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(sink_test_sptr self) -> io_signature_sptr"""
        return _avio505_swig.sink_test_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(sink_test_sptr self) -> long"""
        return _avio505_swig.sink_test_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(sink_test_sptr self) -> basic_block_sptr"""
        return _avio505_swig.sink_test_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(sink_test_sptr self, int ninputs, int noutputs) -> bool"""
        return _avio505_swig.sink_test_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(sink_test_sptr self) -> std::string"""
        return _avio505_swig.sink_test_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(sink_test_sptr self, std::string name)"""
        return _avio505_swig.sink_test_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(sink_test_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _avio505_swig.sink_test_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(sink_test_sptr self) -> swig_int_ptr"""
        return _avio505_swig.sink_test_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(sink_test_sptr self) -> swig_int_ptr"""
        return _avio505_swig.sink_test_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(sink_test_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _avio505_swig.sink_test_sptr_message_subscribers(self, *args, **kwargs)

sink_test_sptr_swigregister = _avio505_swig.sink_test_sptr_swigregister
sink_test_sptr_swigregister(sink_test_sptr)

sink_test_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
sink_test = sink_test.make;

class resta(object):
    """Proxy of C++ gr::avio505::resta class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    def __init__(self, *args, **kwargs): raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    def make():
        """make() -> resta_sptr"""
        return _avio505_swig.resta_make()

    make = staticmethod(make)
    __swig_destroy__ = _avio505_swig.delete_resta
    __del__ = lambda self : None;
resta_swigregister = _avio505_swig.resta_swigregister
resta_swigregister(resta)

def resta_make():
  """resta_make() -> resta_sptr"""
  return _avio505_swig.resta_make()

class resta_sptr(object):
    """Proxy of C++ boost::shared_ptr<(gr::avio505::resta)> class"""
    thisown = _swig_property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc='The membership flag')
    __repr__ = _swig_repr
    def __init__(self, *args): 
        """
        __init__(boost::shared_ptr<(gr::avio505::resta)> self) -> resta_sptr
        __init__(boost::shared_ptr<(gr::avio505::resta)> self, resta p) -> resta_sptr
        """
        this = _avio505_swig.new_resta_sptr(*args)
        try: self.this.append(this)
        except: self.this = this
    def __deref__(self):
        """__deref__(resta_sptr self) -> resta"""
        return _avio505_swig.resta_sptr___deref__(self)

    __swig_destroy__ = _avio505_swig.delete_resta_sptr
    __del__ = lambda self : None;
    def make(self):
        """make(resta_sptr self) -> resta_sptr"""
        return _avio505_swig.resta_sptr_make(self)

    def history(self):
        """history(resta_sptr self) -> unsigned int"""
        return _avio505_swig.resta_sptr_history(self)

    def declare_sample_delay(self, *args):
        """
        declare_sample_delay(resta_sptr self, int which, int delay)
        declare_sample_delay(resta_sptr self, unsigned int delay)
        """
        return _avio505_swig.resta_sptr_declare_sample_delay(self, *args)

    def sample_delay(self, *args, **kwargs):
        """sample_delay(resta_sptr self, int which) -> unsigned int"""
        return _avio505_swig.resta_sptr_sample_delay(self, *args, **kwargs)

    def output_multiple(self):
        """output_multiple(resta_sptr self) -> int"""
        return _avio505_swig.resta_sptr_output_multiple(self)

    def relative_rate(self):
        """relative_rate(resta_sptr self) -> double"""
        return _avio505_swig.resta_sptr_relative_rate(self)

    def start(self):
        """start(resta_sptr self) -> bool"""
        return _avio505_swig.resta_sptr_start(self)

    def stop(self):
        """stop(resta_sptr self) -> bool"""
        return _avio505_swig.resta_sptr_stop(self)

    def nitems_read(self, *args, **kwargs):
        """nitems_read(resta_sptr self, unsigned int which_input) -> uint64_t"""
        return _avio505_swig.resta_sptr_nitems_read(self, *args, **kwargs)

    def nitems_written(self, *args, **kwargs):
        """nitems_written(resta_sptr self, unsigned int which_output) -> uint64_t"""
        return _avio505_swig.resta_sptr_nitems_written(self, *args, **kwargs)

    def max_noutput_items(self):
        """max_noutput_items(resta_sptr self) -> int"""
        return _avio505_swig.resta_sptr_max_noutput_items(self)

    def set_max_noutput_items(self, *args, **kwargs):
        """set_max_noutput_items(resta_sptr self, int m)"""
        return _avio505_swig.resta_sptr_set_max_noutput_items(self, *args, **kwargs)

    def unset_max_noutput_items(self):
        """unset_max_noutput_items(resta_sptr self)"""
        return _avio505_swig.resta_sptr_unset_max_noutput_items(self)

    def is_set_max_noutput_items(self):
        """is_set_max_noutput_items(resta_sptr self) -> bool"""
        return _avio505_swig.resta_sptr_is_set_max_noutput_items(self)

    def set_min_noutput_items(self, *args, **kwargs):
        """set_min_noutput_items(resta_sptr self, int m)"""
        return _avio505_swig.resta_sptr_set_min_noutput_items(self, *args, **kwargs)

    def min_noutput_items(self):
        """min_noutput_items(resta_sptr self) -> int"""
        return _avio505_swig.resta_sptr_min_noutput_items(self)

    def max_output_buffer(self, *args, **kwargs):
        """max_output_buffer(resta_sptr self, int i) -> long"""
        return _avio505_swig.resta_sptr_max_output_buffer(self, *args, **kwargs)

    def set_max_output_buffer(self, *args):
        """
        set_max_output_buffer(resta_sptr self, long max_output_buffer)
        set_max_output_buffer(resta_sptr self, int port, long max_output_buffer)
        """
        return _avio505_swig.resta_sptr_set_max_output_buffer(self, *args)

    def min_output_buffer(self, *args, **kwargs):
        """min_output_buffer(resta_sptr self, int i) -> long"""
        return _avio505_swig.resta_sptr_min_output_buffer(self, *args, **kwargs)

    def set_min_output_buffer(self, *args):
        """
        set_min_output_buffer(resta_sptr self, long min_output_buffer)
        set_min_output_buffer(resta_sptr self, int port, long min_output_buffer)
        """
        return _avio505_swig.resta_sptr_set_min_output_buffer(self, *args)

    def pc_noutput_items(self):
        """pc_noutput_items(resta_sptr self) -> float"""
        return _avio505_swig.resta_sptr_pc_noutput_items(self)

    def pc_noutput_items_avg(self):
        """pc_noutput_items_avg(resta_sptr self) -> float"""
        return _avio505_swig.resta_sptr_pc_noutput_items_avg(self)

    def pc_noutput_items_var(self):
        """pc_noutput_items_var(resta_sptr self) -> float"""
        return _avio505_swig.resta_sptr_pc_noutput_items_var(self)

    def pc_nproduced(self):
        """pc_nproduced(resta_sptr self) -> float"""
        return _avio505_swig.resta_sptr_pc_nproduced(self)

    def pc_nproduced_avg(self):
        """pc_nproduced_avg(resta_sptr self) -> float"""
        return _avio505_swig.resta_sptr_pc_nproduced_avg(self)

    def pc_nproduced_var(self):
        """pc_nproduced_var(resta_sptr self) -> float"""
        return _avio505_swig.resta_sptr_pc_nproduced_var(self)

    def pc_input_buffers_full(self, *args):
        """
        pc_input_buffers_full(resta_sptr self, int which) -> float
        pc_input_buffers_full(resta_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.resta_sptr_pc_input_buffers_full(self, *args)

    def pc_input_buffers_full_avg(self, *args):
        """
        pc_input_buffers_full_avg(resta_sptr self, int which) -> float
        pc_input_buffers_full_avg(resta_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.resta_sptr_pc_input_buffers_full_avg(self, *args)

    def pc_input_buffers_full_var(self, *args):
        """
        pc_input_buffers_full_var(resta_sptr self, int which) -> float
        pc_input_buffers_full_var(resta_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.resta_sptr_pc_input_buffers_full_var(self, *args)

    def pc_output_buffers_full(self, *args):
        """
        pc_output_buffers_full(resta_sptr self, int which) -> float
        pc_output_buffers_full(resta_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.resta_sptr_pc_output_buffers_full(self, *args)

    def pc_output_buffers_full_avg(self, *args):
        """
        pc_output_buffers_full_avg(resta_sptr self, int which) -> float
        pc_output_buffers_full_avg(resta_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.resta_sptr_pc_output_buffers_full_avg(self, *args)

    def pc_output_buffers_full_var(self, *args):
        """
        pc_output_buffers_full_var(resta_sptr self, int which) -> float
        pc_output_buffers_full_var(resta_sptr self) -> pmt_vector_float
        """
        return _avio505_swig.resta_sptr_pc_output_buffers_full_var(self, *args)

    def pc_work_time(self):
        """pc_work_time(resta_sptr self) -> float"""
        return _avio505_swig.resta_sptr_pc_work_time(self)

    def pc_work_time_avg(self):
        """pc_work_time_avg(resta_sptr self) -> float"""
        return _avio505_swig.resta_sptr_pc_work_time_avg(self)

    def pc_work_time_var(self):
        """pc_work_time_var(resta_sptr self) -> float"""
        return _avio505_swig.resta_sptr_pc_work_time_var(self)

    def pc_work_time_total(self):
        """pc_work_time_total(resta_sptr self) -> float"""
        return _avio505_swig.resta_sptr_pc_work_time_total(self)

    def pc_throughput_avg(self):
        """pc_throughput_avg(resta_sptr self) -> float"""
        return _avio505_swig.resta_sptr_pc_throughput_avg(self)

    def set_processor_affinity(self, *args, **kwargs):
        """set_processor_affinity(resta_sptr self, std::vector< int,std::allocator< int > > const & mask)"""
        return _avio505_swig.resta_sptr_set_processor_affinity(self, *args, **kwargs)

    def unset_processor_affinity(self):
        """unset_processor_affinity(resta_sptr self)"""
        return _avio505_swig.resta_sptr_unset_processor_affinity(self)

    def processor_affinity(self):
        """processor_affinity(resta_sptr self) -> std::vector< int,std::allocator< int > >"""
        return _avio505_swig.resta_sptr_processor_affinity(self)

    def active_thread_priority(self):
        """active_thread_priority(resta_sptr self) -> int"""
        return _avio505_swig.resta_sptr_active_thread_priority(self)

    def thread_priority(self):
        """thread_priority(resta_sptr self) -> int"""
        return _avio505_swig.resta_sptr_thread_priority(self)

    def set_thread_priority(self, *args, **kwargs):
        """set_thread_priority(resta_sptr self, int priority) -> int"""
        return _avio505_swig.resta_sptr_set_thread_priority(self, *args, **kwargs)

    def name(self):
        """name(resta_sptr self) -> std::string"""
        return _avio505_swig.resta_sptr_name(self)

    def symbol_name(self):
        """symbol_name(resta_sptr self) -> std::string"""
        return _avio505_swig.resta_sptr_symbol_name(self)

    def input_signature(self):
        """input_signature(resta_sptr self) -> io_signature_sptr"""
        return _avio505_swig.resta_sptr_input_signature(self)

    def output_signature(self):
        """output_signature(resta_sptr self) -> io_signature_sptr"""
        return _avio505_swig.resta_sptr_output_signature(self)

    def unique_id(self):
        """unique_id(resta_sptr self) -> long"""
        return _avio505_swig.resta_sptr_unique_id(self)

    def to_basic_block(self):
        """to_basic_block(resta_sptr self) -> basic_block_sptr"""
        return _avio505_swig.resta_sptr_to_basic_block(self)

    def check_topology(self, *args, **kwargs):
        """check_topology(resta_sptr self, int ninputs, int noutputs) -> bool"""
        return _avio505_swig.resta_sptr_check_topology(self, *args, **kwargs)

    def alias(self):
        """alias(resta_sptr self) -> std::string"""
        return _avio505_swig.resta_sptr_alias(self)

    def set_block_alias(self, *args, **kwargs):
        """set_block_alias(resta_sptr self, std::string name)"""
        return _avio505_swig.resta_sptr_set_block_alias(self, *args, **kwargs)

    def _post(self, *args, **kwargs):
        """_post(resta_sptr self, swig_int_ptr which_port, swig_int_ptr msg)"""
        return _avio505_swig.resta_sptr__post(self, *args, **kwargs)

    def message_ports_in(self):
        """message_ports_in(resta_sptr self) -> swig_int_ptr"""
        return _avio505_swig.resta_sptr_message_ports_in(self)

    def message_ports_out(self):
        """message_ports_out(resta_sptr self) -> swig_int_ptr"""
        return _avio505_swig.resta_sptr_message_ports_out(self)

    def message_subscribers(self, *args, **kwargs):
        """message_subscribers(resta_sptr self, swig_int_ptr which_port) -> swig_int_ptr"""
        return _avio505_swig.resta_sptr_message_subscribers(self, *args, **kwargs)

resta_sptr_swigregister = _avio505_swig.resta_sptr_swigregister
resta_sptr_swigregister(resta_sptr)

resta_sptr.__repr__ = lambda self: "<gr_block %s (%d)>" % (self.name(), self.unique_id())
resta = resta.make;



